### PR TITLE
Upgraded versions to be able to use new plugin interface

### PR DESCRIPTION
**Pull request by leggebroten**
Upgraded to be able to use new version of TypedStruct's plugin interface and added test to prove that it would work with custom Ecto types

### CODE REVIEW

**Comment by tino415** [comment]
Thank you, very nice, could modify version to 1.0.0, I think this is breaking change for people working with older versions, I gladly will release it after that.

**Review by tino415 — APPROVED** [review]

**Comment by leggebroten** [comment]
@tino415 
Glad to do that.

Question for you.  
The original `Typed_Struct` repo hasn't had any attention from maintainers in awhile.  They've even failed to reply to folks that want to move it into core.
https://github.com/ejpcmac/typed_struct

Somebody has forked it and seems to be investing heavily but, because of how Hex works, had to rename it.
https://github.com/saleyn/typedstruct

It would be nice to have a "plugins" section added to the `typed_struct` repo to direct them here, but that would mean using the new maintained `typedstruct` repo

Thoughts?

**Comment by tino415** [comment]
But not sure if I should also not create fork and publish different version of this package. What do you think? It make sense to me that people using original would also like to be able to use this library.

**Comment by leggebroten** [comment]
@tino415 
There are a couple plugins we've developed that are dependent on your plugin that could have widespread usage w/i the community.  One to trivialize creating validated structs, and another that make basic OTLP tracing trivial.

Unfortunately, because the `Typed_Struct` source Repo isn't being maintained any longer, your Repo too will become unusable shortly unless users fork their own `Typed_Struct` and that would be a shame.

Do you have a way to contact the owner?
Or maybe there's a way to take ownership of the original Repo?

**Pull request merged**
